config/routes.rb
Rails.application.routes.draw do
  # get 'boards'          => 'boards#index'
  # get 'boards/new'      => 'boards#new'
  # post 'boards'         => 'boards#create'
  # get 'boards/:id'      => 'boards#show'
  # get 'boards/:id/edit' => 'boards#edit'
  # put 'boards/:id'      => 'boards#update'
  # delete 'boards/:id'   => 'boards#destroy'
  resources :boards do
    resources :comments, only: [:create, :destroy]
  end

  # root boards_path
  root to: 'boards#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  has_many :comments, dependent: :destroy
  

  validates :title, presence: true, length: { in: 4..127 }
  validates :editor, presence: true, length: { in: 1..30 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :board

  validates :board, presence: true
  validates :name, presence: true
  validates :content, presence: true, length: { in: 1..1000 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  def index
    @boards = Board.all
  end

  def new
    @board = Board.new
  end

  def create
    @board = Board.new(params_board)
    if @board.save
      redirect_to board_url(@board)
    else
      render "new"
    end
  end

  def show
    @board = Board.includes(:comments).find(params[:id])
    @comment = Comment.new
  end

  def edit
    @board = Board.find(params[:id])
  end

  def update
    @board = Board.find(params[:id])
    if @board.update_attributes(params_board)
      redirect_to board_url(@board)
    else
      render "edit"
    end
  end

  def destroy
    @board = Board.find(params[:id])
    @board.destroy
    redirect_to boards_url
  end

  private

    def params_board
      params.require(:board).permit(:title, :editor)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @board = Board.find(params[:board_id])
    @comment = Comment.new(params_comment)
    @comment.board = @board

    if @comment.save
      redirect_to board_url(@board)
    else
      rendre "boards/show"
    end
  end

  def destroy
    @board = Board.find(params[:board_id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to board_url(@board)
  end

  private

  def params_comment
    params.require(:comment).permit(:name, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boards/edit.html.erb
<div class="wrapper wrapper__bg">
  <div class="container">
  <%= link_to @board.title, board_path(@board) %>
  <hr>
  <h1>Boards#edit</h1>
  <% if @board.errors.any? %>
  <%= @board.errors.full_messages %>
  <% end %>
    <div class="panel form">
    <%= form_for @board do |f| %>
    <div>
    <div class="form--label">タイトル: </div>
    <div class="form--input">
    <%= f.text_field :title %>
    </div>
    </div>
    <div>
    <div class="form--label">作成者名:</div>
    <div class="form--input">
    <%= f.text_field :editor %>
    </div>
    </div>
    <%= f.submit %>
    <% end %>
    </div>
    </div>
   </div>

app/views/boards/index.html.erb
<div class="wrapper wrapper__bg">
  <div class="container">
      <h1>2chクローン</h1>
    <%= link_to "スレッド新規作成", new_board_path %>
    <hr>
      <div class="panel">
      <% @boards.each do |board| %>
        <%= link_to board.title, board_path(board) %><br>
      <% end %>
      </div>
  </div>
</div>

app/views/boards/new.html.erb
 <div class="wrapper wrapper__bg">
  <div class="container">
  <%= link_to "スレッド一覧に戻る", boards_path %>
  <hr>
  <h1>Boards#new</h1>
  <% if @board.errors.any? %>
    <%= @board.errors.full_messages %>
  <% end %>
    <div class="panel form">
    <%= form_for @board do |f| %>
    <div>
    <div class="form--label">タイトル: </div>
    <div class="form--input">
    <%= f.text_field :title %>
    </div>
    </div>
    <div>
    <div class="form--label">作成者名: </div>
    <div class="form--input">
    <%= f.text_field :editor %>
    </div>
    </div>
    <%= f.submit %>
    <% end %>
    </div>
    </div>
   </div> 

app/views/boards/show.html.erb
<div class="wrapper wrapper__bg">
  <div class="container">
     <%= link_to "スレッド一覧に戻る", boards_path %>
     <hr>
    <div class="board">
      <h1 class="board--name"><%= @board.title %></h1>
    </div>
     <%= link_to "タイトルを編集する", edit_board_path(@board) %>
      <%= link_to "削除する", board_path(@board), method: :delete, data: { confirm: "本当に削除しますか？" } %>
      <hr>
      <div class="comments">
  <% @board.comments.each_with_index do |comment, index| %>
    <div class="comment">
    <div class="comment--heading">
      <%= index + 1 %>：
      <%= comment.name %>：
      <%= comment.created_at.strftime("%Y/%m/%d %H:%M:%S ") %>：
      <%= link_to "削除する", board_comment_path(@board, comment), method: :delete, data: { confirm: "本当に削除しますか?" } %> <br>
      </div>
      <div class="comment-body">
        <%= comment.content %>
      </div>
    </div>
        <% end %>
      </div>
      <hr>
      <%= form_for @comment, url: board_comments_path(@board, @comment) do |f| %>
      名前：<%= f.text_field :name %><br>
      コメント：<%= f.text_area :content %><br>
      <%= f.submit %>
      <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>